README.md
content/00.build/90.contributing-to-documentation/20.contribution-guidelines.md

Update Readme and Contribution Guidelines with better description of how to contribute and make commits.
Also edited some formatting slightly for readability.

Update contribution docs

---

.github/workflows/check-pr-title.yaml

Add PR Title check on PRs to ensure title follows Conventional Commits standards.

chore: add pr title check workflow

---

.github/workflows/check-pr-title.yaml

Update version of pr title check
Superficial changes to the pr title check workflow.

chore: modify pr title check

---

.github/workflows/check-pr-title.yaml

Fix the permissions on Check PR Title action

chore: add additional permissions to pr title check

---

content/30.ecosystem/90.node-providers.md

Add Blast API to Provider list

docs: Add Blast API in Provider's list - Update 90.node-providers.md

---

content/00.build/65.developer-reference/15.migrate-era-to-chain.md
content/00.build/65.developer-reference/50.era-contracts/25.l1-ecosystem-contracts.md
content/00.build/65.developer-reference/50.era-contracts/30.pubdata-post-4844.md
content/00.build/65.developer-reference/50.era-contracts/60.elliptic-curve-precompiles.md

Changes Made to Docs:
* Precompiles
* Post 4844
* Migration Process
* L1 Ecosystem Contracts

docs: Updates as per the v24 release

---

package.json

Testing out the capability of using Stackblitz's Codeflow

chore: add config for stackblitz

---

content/00.build/70.api-reference/20.zks-rpc.md

Fix errors in RPC API for the `zks` namespace.

fix(build,api-refernce): fix erros in RPC API for the `zks` namespace

---

content/00.build/65.developer-reference/10.protocol.md

Fixed mispelling in protocol page.

fix: update 10.protocol.md

---

content/00.build/05.quick-start/3.deploy-your-first-contract.md

Adds video to the quickstart tutorial

chore: update tutorial with video

---

content/00.build/05.quick-start/3.deploy-your-first-contract.md

chore: Update 3.deploy-your-first-contract.md

---

content/10.zk-stack/10.components/70.compiler/20.specification/70.binary-layout.md

fix: typos in binary layout document

---

content/10.zk-stack/05.concepts/00.transaction-lifecycle.md

fix: formatting in transaction-lifecycle.md

---

content/00.build/05.start-coding/10.zksync-101/_deploy_factory/_foundry_deploy_contract_factory.md

update contract factory foundry to remove `--sender` and `--factory-deps` from `create` and `cast`

fix: Update _foundry_deploy_contract_factory.md

---

README.md
content/00.build/65.developer-reference/12.addresses/80.zk-chain-addresses.md

* Cleaned up the page with contract addresses.
* Added small explanation for people who are having issues with github api.

fix: cleanup contract addresses

---

content/30.ecosystem/60.network-faucets.md

- added Getblock as a ZKsync testnet faucet
- changed format for faucets to a table view

chore: Add-faucet

---

content/00.build/70.api-reference/_partials/_call-request-params.md

API endpoint request body example has incorrect field.
N/A
Reported by partner

fix: replaces with customData

---

firebase.json

Fix redirects that were misspelled and broken.

fix: sdk redirects

---

server/api/search.json.get.ts

Edit search params query so that it doesn't pull and show partials in the search results. These are what are 404'ing.

fix: search params

---

content/00.build/05.start-coding/10.zksync-101/_upgrading/_beacon_proxy_contract_upgradability.md
content/00.build/05.start-coding/10.zksync-101/_upgrading/_uups_contract_upgradability.md

update docs to what is shown in terminal
related to https://github.com/matter-labs/zksync-contract-templates/pull/23

fix: update 101 template outputs

---

content/10.zk-stack/20.running-a-zk-chain/30.custom-base-tokens.md

minor fix for custom ERC20 token steps

docs: fix order of steps for ERC20 base tokens

---

content/00.build/60.test-and-debug/20.in-memory-node.md

Add `Debug Transactions & Smart Contracts` to In-Memory Node docs

feat: add debug-mode to in-memory-node

---

content/00.build/40.tooling/20.hardhat/20.migrating-to-zksync.md

- should be upgradeBeacon instead of upgradeProxy

fix: fix typo in migration guide for hh
